singleQuote: true
semi: true
printWidth: 100
trailingComma: all
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-tailwindcss
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
tailwindStylesheet: src/renderer/src/app.css
